package lt.vu.mybatis.dao;

import java.util.List;

import lt.vu.entities.Review;
import org.mybatis.cdi.Mapper;

@Mapper
public interface ReviewMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    int insert(Review record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    Review selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    List<Review> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.REVIEW
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    int updateByPrimaryKey(Review record);
}