package lt.vu.mybatis.model;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.ID
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.TITLE
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    private String title;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.ID
     *
     * @return the value of PUBLIC.MOVIE.ID
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.ID
     *
     * @param id the value for PUBLIC.MOVIE.ID
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.TITLE
     *
     * @return the value of PUBLIC.MOVIE.TITLE
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.TITLE
     *
     * @param title the value for PUBLIC.MOVIE.TITLE
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    public void setTitle(String title) {
        this.title = title;
    }
}