package lt.vu.mybatis.model;

public class Review {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REVIEW.ID
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    private Integer id;

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REVIEW.NAME
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    private String name;
    private String text;
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REVIEW.RATING
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    private Integer rating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.REVIEW.MOVIE_ID
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    private Integer movieId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REVIEW.ID
     *
     * @return the value of PUBLIC.REVIEW.ID
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REVIEW.ID
     *
     * @param id the value for PUBLIC.REVIEW.ID
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REVIEW.NAME
     *
     * @return the value of PUBLIC.REVIEW.NAME
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REVIEW.NAME
     *
     * @param name the value for PUBLIC.REVIEW.NAME
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REVIEW.RATING
     *
     * @return the value of PUBLIC.REVIEW.RATING
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    public Integer getRating() {
        return rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REVIEW.RATING
     *
     * @param rating the value for PUBLIC.REVIEW.RATING
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    public void setRating(Integer rating) {
        this.rating = rating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.REVIEW.MOVIE_ID
     *
     * @return the value of PUBLIC.REVIEW.MOVIE_ID
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    public Integer getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.REVIEW.MOVIE_ID
     *
     * @param movieId the value for PUBLIC.REVIEW.MOVIE_ID
     *
     * @mbg.generated Sat Apr 30 20:15:13 EEST 2022
     */
    public void setMovieId(Integer movieId) {
        this.movieId = movieId;
    }
}